kind: Secret
apiVersion: v1
metadata:
  name: apple-secret
  namespace: apple
  annotations:
    avp.kubernetes.io/path: "kv-indonesia/data/jawabarat"
type: Opaque
stringData:
  city: <city>
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: apple-configmap
  namespace: apple
  annotations:
    avp.kubernetes.io/path: "kv-indonesia/data/jawabarat"
data:
  country: <country>
