kind: Secret
apiVersion: v1
metadata:
  name: apple-secret
  namespace: apple
  annotations:
    avp.kubernetes.io/path: "kv-indonesia/data/jawabarat"
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  city: <sample>