apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fruitsingress
  namespace: orange
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "*"
      http:
        paths:
          - backend:
              serviceName: orangeservice
              servicePort: 5678
