apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fruitsingress
  namespace: orange
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: orangeservice
              servicePort: 5678
