apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fruitsingress
  namespace: orange
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /orange
            backend:
              serviceName: orangeservice
              servicePort: 5678
